# Generated by Django 3.1.7 on 2021-05-22 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dogum_gunu',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 19, 9, 34, 832331), verbose_name='Doğum Günü'),
        ),
    ]
