# Generated by Django 3.1.7 on 2021-10-14 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='survey_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Anket Katılımcısı'),
        ),
        migrations.AlterField(
            model_name='surveyanswerfromquestionchoice',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.multiplechoice', verbose_name='Çoktan Seçmeli Cevabı'),
        ),
        migrations.AlterField(
            model_name='surveyanswerfromquestionoption',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.optionchoice', verbose_name='Dropdown Cevabı'),
        ),
    ]
