# Generated by Django 3.1.7 on 2021-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_batch_batch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='bulk_file',
            field=models.FileField(blank=True, null=True, upload_to='excel', verbose_name='Excel Dosyası'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='firm_logo_135',
            field=models.FileField(blank=True, null=True, upload_to='article_images', verbose_name='Firma Logosu'),
        ),
    ]
