# Generated by Django 3.1.7 on 2021-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211017_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_image',
            field=models.FileField(blank=True, help_text='Fotoğrafınızın boyutunun 150x150 olmasına dikkat edin', null=True, upload_to='content_images', verbose_name='Content Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='firm_logo',
            field=models.FileField(blank=True, null=True, upload_to='firm_logos', verbose_name='Firma Logosu'),
        ),
    ]
