# Generated by Django 3.1.7 on 2021-05-24 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210523_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dogum_gunu',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Doğum Günü'),
        ),
    ]
