# Generated by Django 3.1.7 on 2021-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211017_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_description',
            field=models.TextField(null=True, verbose_name='Content Açıklaması'),
        ),
    ]
