# Generated by Django 3.1.7 on 2021-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210524_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dogum_gunu',
            field=models.DateTimeField(default='<built-in method now of type object at 0x00007FFF89F65650>', verbose_name='Doğum Günü'),
        ),
    ]
