# Generated by Django 3.1.7 on 2021-10-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211018_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='firm',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.firm'),
        ),
    ]
