# Generated by Django 3.1.7 on 2021-10-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211022_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Yazı İçeriği', 'verbose_name_plural': 'Yazı İçerikleri'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': "Batch'ler"},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Girişim', 'verbose_name_plural': 'Girişimler'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'İçerik', 'verbose_name_plural': 'İçerikler'},
        ),
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmalar'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Modül', 'verbose_name_plural': 'Modüller'},
        ),
        migrations.AlterModelOptions(
            name='multiplequestion',
            options={'ordering': ('q_order',), 'verbose_name': 'Çoktan Seçmeli Soru', 'verbose_name_plural': 'Çoktan Seçmeli Sorular'},
        ),
        migrations.AlterModelOptions(
            name='optionquestion',
            options={'ordering': ('q_order',), 'verbose_name': 'Açılır Menülü Soru', 'verbose_name_plural': 'Açılır Menülü Sorular'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Anket', 'verbose_name_plural': 'Anketler'},
        ),
        migrations.AlterModelOptions(
            name='surveyanswer',
            options={'verbose_name': 'Anket Cevabı', 'verbose_name_plural': 'Anket Cevapları'},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={'ordering': ('q_order',), 'verbose_name': 'Text Sorusu', 'verbose_name_plural': 'Text Soruları'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video İçeriği', 'verbose_name_plural': 'Video İçerikleri'},
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=254, verbose_name='Slug'),
        ),
    ]
