# Generated by Django 3.1.7 on 2021-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210527_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_teamleader',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
