# Generated by Django 3.1.7 on 2021-10-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.firm'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_image',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/content-image.jpg', help_text='Fotoğrafınızın boyutunun 150x150 olmasına dikkat edin', null=True, upload_to='content_images', verbose_name='Content Fotoğrafı'),
        ),
    ]
