# Generated by Django 3.1.7 on 2021-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210527_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_teamleader',
            field=models.BooleanField(null=True, verbose_name='Ekip Lideri'),
        ),
    ]
