# Generated by Django 3.1.7 on 2021-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210531_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_size', models.IntegerField(blank=True, verbose_name='Ekip Büyüklüğü')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='team_size',
            new_name='company_name',
        ),
    ]
