# Generated by Django 3.1.7 on 2021-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210607_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enterprise_summary',
            field=models.CharField(max_length=450, null=True, verbose_name='Girişim Özeti'),
        ),
    ]
