# Generated by Django 3.1.7 on 2021-06-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210609_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(choices=[('Animally', 'Animally'), ('Aquapure', 'Aquapure'), ('Arte/Make', 'Arte/Make'), ('Balkız', 'Balkız'), ('Bamboo', 'Bamboo'), ('Biged', 'Biged'), ('Cardpool', 'Cardpool'), ('Cepte Sevgi', 'Cepte Sevgi'), ('CezerUni', 'CezerUni'), ('ÇİBA APP', 'ÇİBA APP'), ('Cli̇ck Enerji̇', 'Cli̇ck Enerji̇'), ('Cloudbox', 'Cloudbox'), ('Comet', 'Comet'), ('Create Yourself', 'Create Yourself'), ('Dice Eğitim Setleri', 'Dice Eğitim Setleri'), ('DonationToken', 'DonationToken'), ('Ecotap', 'Ecotap'), ('Elimi Tut', 'Elimi Tut'), ('ENGELSİZ İLETİŞİM', 'ENGELSİZ İLETİŞİM'), ('ERILUM', 'ERILUM'), ('E-Şifa', 'E-Şifa'), ('EvdenEle', 'EvdenEle'), ('FilthreeX', 'FilthreeX'), ('Fişyo', 'Fişyo'), ('FOODIES', 'FOODIES'), ('FoodPro', 'FoodPro'), ('Freedom', 'Freedom'), ('FullArt', 'FullArt'), ('Gel Gel', 'Gel Gel'), ('Girişimciler İçin Girişim', 'Girişimciler İçin Girişim'), ('Götürelim', 'Götürelim'), ('Gübregaz', 'Gübregaz'), ('GÜCÜNÜ BİZDEN AL', 'GÜCÜNÜ BİZDEN AL'), ('Günsu', 'Günsu'), ('GüvenEli', 'GüvenEli'), ('Hidromotor', 'Hidromotor'), ('International Student ID', 'International Student ID'), ('Kablosuz Holter', 'Kablosuz Holter'), ('Kardelen', 'Kardelen'), ('Kiddy Kit', 'Kiddy Kit'), ('Kitapevski', 'Kitapevski'), ('KitAPP', 'KitAPP'), ('Kozmodrop', 'Kozmodrop'), ('Kutu', 'Kutu'), ('LUKOMETR', 'LUKOMETR'), ('Medicurism', 'Medicurism'), ('Meliloto', 'Meliloto'), ('MultiMindsAI', 'MultiMindsAI'), ('Musicowboy', 'Musicowboy'), ('No-fogfacemask', 'No-fogfacemask'), ('Nonzheimer', 'Nonzheimer'), ('Now we see too', 'Now we see too'), ('Pati İzi', 'Pati İzi'), ('PatyVer', 'PatyVer'), ('PenFriends', 'PenFriends'), ('Petsgram', 'Petsgram'), ('Pi̇si̇kocep', 'Pi̇si̇kocep'), ('Plastiği Yeniden Amaçlandırma', 'Plastiği Yeniden Amaçlandırma'), ('PREDECIR', 'PREDECIR'), ('Quik Roam', 'Quik Roam'), ('Sanreal Kütüphane', 'Sanreal Kütüphane'), ('SATÜ', 'SATÜ'), ('SelfCycle', 'SelfCycle'), ('Si-Ro', 'Si-Ro'), ('Social Jam', 'Social Jam'), ('Step', 'Step'), ('STEP Tim', 'STEP Tim'), ('Stok Ürün', 'Stok Ürün'), ('Studygether', 'Studygether'), ('Stutools', 'Stutools'), ('TabulaRasa', 'TabulaRasa'), ('Tamir Plus', 'Tamir Plus'), ('Tarımda Otomasyon', 'Tarımda Otomasyon'), ('Tester', 'Tester'), ('TETA', 'TETA'), ('ÜNİDEN', 'ÜNİDEN'), ('Univasyon', 'Univasyon'), ('Vanswap', 'Vanswap'), ('Yükselen Patatesler Topraksız Tarım', 'Yükselen Patatesler Topraksız Tarım'), ('Zappmatch', 'Zappmatch')], default='Animally', max_length=250, verbose_name='Girişim Adı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', unique=True),
        ),
    ]
