# Generated by Django 3.1.7 on 2021-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210614_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prospect',
            new_name='firm',
        ),
        migrations.AddField(
            model_name='firm',
            name='bulk_file',
            field=models.FileField(null=True, upload_to='excel/', verbose_name='Excel Dosyası'),
        ),
    ]
