# Generated by Django 3.1.7 on 2021-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210625_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_firm_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Firma Yöneticisi'),
        ),
    ]
