# Generated by Django 3.1.7 on 2021-09-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210909_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=250, verbose_name='Modül Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_header', models.CharField(max_length=350, verbose_name='Anket Başlığı')),
                ('survey_description', models.TextField(verbose_name='Anket Açıklaması')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Oluşturma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_header', models.CharField(max_length=350, verbose_name='Video Başlığı')),
                ('article_description', models.TextField(verbose_name='Video Açıklaması')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Oluşturma Tarihi')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='Videos')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=250, verbose_name='İçerik Tipi')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.article')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.survey')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.video')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=250, verbose_name='Batch Adı')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.module')),
            ],
        ),
    ]
