# Generated by Django 3.1.7 on 2021-09-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210917_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Video', 'Video'), ('Anket', 'Anket')], max_length=250, verbose_name='İçerik Tipi'),
        ),
    ]
